-- MySQL Script generated by MySQL Workbench
-- Wed 29 Nov 2017 10:20:49 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eolms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS 'eolms' ;

-- -----------------------------------------------------
-- Schema eolms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'eolms' DEFAULT CHARACTER SET utf8 ;
USE 'eolms' ;

-- -----------------------------------------------------
-- Table 'eolms'.'orgs'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'orgs' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'orgname' VARCHAR(50) NOT NULL,
  'orgemail' VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY ('id'),
  UNIQUE INDEX 'orgname' ('orgname' ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'assignments'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'assignments' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'orgid' INT(11) NOT NULL,
  'name' VARCHAR(500) NULL DEFAULT NULL,
  'description' VARCHAR(4500) NULL,
  'assisted' TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_a_orgid_idx' ('orgid' ASC),
  CONSTRAINT 'fk_a_orgid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'content_types'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'content_types' (
  'id' INT(11) NOT NULL,
  'type' VARCHAR(20) NOT NULL,
  PRIMARY KEY ('id'))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'users'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'users' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'password' VARCHAR(50) NOT NULL,
  'firstname' VARCHAR(50) NOT NULL,
  'lastname' VARCHAR(50) NOT NULL,
  'emailaddress' VARCHAR(80) NOT NULL,
  'accountcreatedtime' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  'accountclosedtime' TIMESTAMP NULL,
  'status' INT(11) NULL DEFAULT '0',
  'question' VARCHAR(50) DEFAULT NULL,
  'answer' VARCHAR(50) DEFAULT NULL, 
  PRIMARY KEY ('id'),
  UNIQUE INDEX 'emailaddress' ('emailaddress' ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'clients_assignments'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'clients_assignments' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'clientid' INT(11) NOT NULL,
  'assignmentid' INT(11) NOT NULL,
  'duedate' DATE NOT NULL DEFAULT '2017-12-30',
  PRIMARY KEY ('id'),
  INDEX 'fk_ca_clientid' ('clientid' ASC),
  INDEX 'fk_ca_assignmentid_idx' ('assignmentid' ASC),
  CONSTRAINT 'fk_ca_assignmentid'
    FOREIGN KEY ('assignmentid')
    REFERENCES 'eolms'.'assignments' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT 'fk_ca_clientid'
    FOREIGN KEY ('clientid')
    REFERENCES 'eolms'.'users' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'consultant_clients'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'consultant_clients' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'orgid' INT(11) NOT NULL,
  'consultantid' INT(11) NOT NULL,
  'clientid' INT(11) NOT NULL,
  'createdtime' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  'closedtime' TIMESTAMP NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_cc_orgid' ('orgid' ASC),
  INDEX 'fk_cc_consultantid' ('consultantid' ASC),
  INDEX 'fk_cc_clientid' ('clientid' ASC),
  CONSTRAINT 'fk_cc_clientid'
    FOREIGN KEY ('clientid')
    REFERENCES 'eolms'.'users' ('id')
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT 'fk_cc_consultantid'
    FOREIGN KEY ('consultantid')
    REFERENCES 'eolms'.'users' ('id'),
  CONSTRAINT 'fk_cc_orgid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id'))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'messages'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'messages' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'status' VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
  'fromid' INT(11) NOT NULL,
  'toid' INT(11) NOT NULL,
  'subject' VARCHAR(50) NULL DEFAULT NULL,
  'message' VARCHAR(511) NOT NULL DEFAULT 'No message.',
  'createdate' DATETIME NOT NULL DEFAULT '2017-10-01 00:00:00',
  'timezone' VARCHAR(12) NOT NULL DEFAULT 'EST',
  PRIMARY KEY ('id'),
  INDEX 'fk_message_fromid' ('fromid' ASC),
  INDEX 'fk_message_toid' ('toid' ASC),
  CONSTRAINT 'fk_message_fromid'
    FOREIGN KEY ('fromid')
    REFERENCES 'eolms'.'users' ('id')
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT 'fk_message_toid'
    FOREIGN KEY ('toid')
    REFERENCES 'eolms'.'users' ('id')
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'notifications'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'notifications' (
  'ID' INT(11) NOT NULL AUTO_INCREMENT,
  'orgid' INT(11) NOT NULL,
  'createdbyid' INT(11) NOT NULL,
  'subject' VARCHAR(80) NOT NULL,
  'note' VARCHAR(200) NOT NULL,
  'startdate' DATETIME NOT NULL DEFAULT '2017-09-01 00:00:00',
  'expirydate' DATETIME NOT NULL DEFAULT '2017-09-01 00:00:00',
  'timezone' VARCHAR(12) NOT NULL DEFAULT 'EST',
  'type' INT(11) NOT NULL DEFAULT '0',

  PRIMARY KEY ('ID'),
  INDEX 'fk_notifications_orgid' ('orgid' ASC),
  INDEX 'fk_notifications_createdbyid' ('createdbyid' ASC),
  CONSTRAINT 'fk_notifications_createdbyid'
    FOREIGN KEY ('createdbyid')
    REFERENCES 'eolms'.'users' ('id')
    ON DELETE CASCADE,
  CONSTRAINT 'fk_notifications_orgid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id')
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'permissions'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'permissions' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'permission' VARCHAR(50) NOT NULL DEFAULT 'user',
  PRIMARY KEY ('id'),
  UNIQUE INDEX 'permission' ('permission' ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'org_user_permissions'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'org_user_permissions' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'orgid' INT(16) NOT NULL,
  'userid' INT(11) NOT NULL,
  'permissionid' INT(11) NOT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_oup_orgid' ('orgid' ASC),
  INDEX 'fk_oup_userid' ('userid' ASC),
  INDEX 'fk_oup_permissionid' ('permissionid' ASC),
  CONSTRAINT 'fk_oup_orgid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id'),
  CONSTRAINT 'fk_oup_permissionid'
    FOREIGN KEY ('permissionid')
    REFERENCES 'eolms'.'permissions' ('id'),
  CONSTRAINT 'fk_oup_userid'
    FOREIGN KEY ('userid')
    REFERENCES 'eolms'.'users' ('id'))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'resources'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'resources' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'name' VARCHAR(20) NULL DEFAULT NULL,
  'resource' MEDIUMBLOB NULL DEFAULT NULL,
  'ext' VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY ('id'))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'orgs_resources'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'orgs_resources' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'orgid' INT(11) NOT NULL,
  'resourceid' INT(11) NOT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_orgresid' ('orgid' ASC),
  INDEX 'fk_resourcesid' ('resourceid' ASC),
  CONSTRAINT 'fk_orgresid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id')
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT 'fk_resourcesid'
    FOREIGN KEY ('resourceid')
    REFERENCES 'eolms'.'resources' ('id')
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'content_items'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'content_items' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'name' VARCHAR(100) NULL,
  'description' VARCHAR(1000) NULL,
  'typeid' INT(11) NOT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_ci_typeid_idx' ('typeid' ASC),
  CONSTRAINT 'fk_ci_typeid'
    FOREIGN KEY ('typeid')
    REFERENCES 'eolms'.'content_types' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'assignment_sequences'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'assignment_sequences' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'assignmentid' INT(11) NOT NULL,
  'contentid' INT(11) NOT NULL,
  'sequencenum' INT(11) NULL DEFAULT 0,
  PRIMARY KEY ('id'),
  INDEX 'fk_as_assignmentid_idx' ('assignmentid' ASC),
  INDEX 'fk_as_contentid_idx' ('contentid' ASC),
  CONSTRAINT 'fk_as_assignmentid'
    FOREIGN KEY ('assignmentid')
    REFERENCES 'eolms'.'assignments' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT 'fk_as_contentid'
    FOREIGN KEY ('contentid')
    REFERENCES 'eolms'.'content_items' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'eolms'.'client_sequence_progress'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'client_sequence_progress' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'clientassignmentid' INT(11) NOT NULL,
  'sequenceid' INT(11) NOT NULL,
  'results' INT(11) NULL DEFAULT 0,
  'completed' TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY ('id'),
  INDEX 'fk_csp_clientassignmentid_idx' ('clientassignmentid' ASC),
  INDEX 'fk_csp_sequenceid_idx' ('sequenceid' ASC),
  CONSTRAINT 'fk_csp_clientassignmentid'
    FOREIGN KEY ('clientassignmentid')
    REFERENCES 'eolms'.'clients_assignments' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT 'fk_csp_sequenceid'
    FOREIGN KEY ('sequenceid')
    REFERENCES 'eolms'.'assignment_sequences' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'eolms'.'client_sequence_usage'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'client_sequence_usage' (
  'id' INT(11) NOT NULL AUTO_INCREMENT,
  'clientsequenceid' INT(11) NOT NULL,
  'starttime' DATETIME NOT NULL DEFAULT '2017-10-01 00:00:00',
  'stoptime' DATETIME NOT NULL DEFAULT '2017-10-01 00:00:00',
  'durationinseconds' INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY ('id'),
  INDEX 'fk_su_clientsequenceid_idx' ('clientsequenceid' ASC),
  CONSTRAINT 'fk_su_clientsequenceid'
    FOREIGN KEY ('clientsequenceid')
    REFERENCES 'eolms'.'client_sequence_progress' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'eolms'.'videos'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'videos' (
  'contentid' INT(11) NOT NULL,
  'videoid' VARCHAR(45) NOT NULL,
  'videoproviderurl' VARCHAR(450) NOT NULL,
  'transcript' LONGTEXT,
  PRIMARY KEY ('contentid'),
  CONSTRAINT 'fk_v_contentid'
    FOREIGN KEY ('contentid')
    REFERENCES 'eolms'.'content_items' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'eolms'.'exams'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'exams' (
  'contentid' INT(11) NOT NULL,
  'examservleturl' VARCHAR(450) NULL,
  PRIMARY KEY ('contentid'),
  CONSTRAINT 'fk_e_contentid'
    FOREIGN KEY ('contentid')
    REFERENCES 'eolms'.'content_items' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'eolms'.'org_content_items'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS 'eolms'.'org_content_items' (
  'id' INT(11) NOT NULL,
  'orgid' INT(11) NOT NULL,
  'contentitemid' INT(11) NOT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_oci_orgid_idx' ('orgid' ASC),
  INDEX 'fk_oci_contentitemid_idx' ('contentitemid' ASC),
  CONSTRAINT 'fk_oci_orgid'
    FOREIGN KEY ('orgid')
    REFERENCES 'eolms'.'orgs' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT 'fk_oci_contentitemid'
    FOREIGN KEY ('contentitemid')
    REFERENCES 'eolms'.'content_items' ('id')
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

/**********************************************************************************************
* create table other_resources
* Author: Robin McGinnis
* 2017-12-02: Created table
**********************************************************************************************/
SET foreign_key_checks = 0; 
DROP TABLE if EXISTS other_resources;

CREATE TABLE IF NOT EXISTS other_resources (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	orgid INTEGER NOT NULL,
	res_name VARCHAR(50),
	res_blob LONGBLOB NOT NULL,
    CONSTRAINT fk_other_resources_orgid FOREIGN KEY (orgid) REFERENCES orgs (id) ON DELETE CASCADE
);
SET foreign_key_checks = 1;